# emacs.nix — Home-manager Emacs module
#
# BEFORE USING: add emacs-overlay to your flake.nix inputs:
#
#   emacs-overlay = {
#     url = "github:nix-community/emacs-overlay";
#     inputs.nixpkgs.follows = "nixpkgs";
#   };
#
# Then add the overlay at the top level of your flake (nixpkgs.overlays or
# in your home/system config), NOT in this module to avoid double-application:
#
#   nixpkgs.overlays = [ inputs.emacs-overlay.overlays.default ];

{ pkgs, inputs, config, lib, ... }:
{
  programs.emacs = {
    enable = true;

    # emacs-pgtk: pure-GTK build for native Wayland support (no XWayland).
    # The emacs-overlay provides this package with --with-native-compilation
    # enabled — Emacs JIT-compiles elisp to native code, big startup/runtime win.
    package = pkgs.emacs-pgtk;

    extraPackages = epkgs: with epkgs; [
      # ── Vim keybinds ──────────────────────────────────
      evil              # vim modal editing in Emacs
      evil-collection   # extends evil to magit, vterm, help buffers, org, etc.

      # ── Keybinding system ─────────────────────────────
      general           # SPC leader key + organized keybind definitions

      # ── Discoverability ───────────────────────────────
      which-key         # shows available keybinds after pressing a prefix
      helpful           # richer help buffers (source code, examples, docstrings)

      # ── Minibuffer completion stack ───────────────────
      # These four work together and are the modern lightweight alternative to helm.
      vertico           # vertical completion list (replaces default horizontal)
      orderless         # space-separated fuzzy filtering in any order
      marginalia        # annotations (docstrings, types) next to candidates
      consult           # enhanced find-file, grep, buffer-switch commands

      # ── In-buffer completion (like nvim-cmp) ──────────
      corfu             # completion popup as you type

      # ── Git ───────────────────────────────────────────
      magit             # the best git interface in any editor, period

      # ── Terminal ──────────────────────────────────────
      vterm             # real terminal emulator via C library (not eshell)

      # ── Org ecosystem ─────────────────────────────────
      org-modern        # visual polish: nicer bullets, checkboxes, tables
      olivetti          # centered/narrowed buffer for writing
      org-roam          # linked notes / Zettelkasten built on org + sqlite

      # ── Language modes ────────────────────────────────
      nix-mode          # nix file support

      # ── Treesitter grammars ───────────────────────────
      # Emacs 29 has built-in treesitter support but needs grammar .so files.
      # Add languages here as you need them.
      (treesit-grammars.with-grammars (g: with g; [
        tree-sitter-nix
        tree-sitter-go
        tree-sitter-python
        tree-sitter-lua
        tree-sitter-bash
        tree-sitter-json
        tree-sitter-yaml
        tree-sitter-toml
      ]))
    ];

    extraConfig = ''
      ;;; init.el — generated by Nix/home-manager
      ;;; Packages are installed via Nix extraPackages above.
      ;;; use-package here is ONLY for configuration and lazy loading —
      ;;; never use :ensure t, Nix handles installation.

      ;; ================================================================
      ;; PERFORMANCE — set before anything else loads
      ;; ================================================================

      ;; Raise GC threshold during startup to avoid pauses while loading.
      ;; 128MB during init, then back to a sane 8MB at runtime.
      (setq gc-cons-threshold (* 128 1024 1024))
      (add-hook 'emacs-startup-hook
                (lambda () (setq gc-cons-threshold (* 8 1024 1024))))

      ;; ================================================================
      ;; CORE UI — strip default chrome, sane defaults
      ;; ================================================================

      ;; Remove toolbar, menu bar, and scroll bar.
      ;; You'll use keybindings for everything — these just waste space.
      (tool-bar-mode   -1)
      (menu-bar-mode   -1)
      (scroll-bar-mode -1)

      ;; No splash screen on startup
      (setq inhibit-startup-message t)

      ;; Show column number in the mode line alongside line number
      (column-number-mode 1)

      ;; Relative line numbers in code and text buffers (like your nvim config)
      (setq display-line-numbers-type 'relative)
      (add-hook 'prog-mode-hook #'display-line-numbers-mode)
      (add-hook 'text-mode-hook #'display-line-numbers-mode)

      ;; Highlight the current line
      (global-hl-line-mode 1)

      ;; Show matching parens
      (show-paren-mode 1)

      ;; Typing with a region selected replaces it (like every other editor)
      (delete-selection-mode 1)

      ;; Spaces not tabs, 2-space indent
      (setq-default indent-tabs-mode nil)
      (setq-default tab-width 2)

      ;; One space after a period, not two
      (setq sentence-end-double-space nil)

      ;; Follow symlinks into version-controlled files without asking
      (setq vc-follow-symlinks t)

      ;; Vertical splits open to the right, horizontal splits open below
      (setq split-height-threshold nil
            split-width-threshold  80)

      ;; Keep Emacs's backup and auto-save files out of your working directories
      (setq backup-directory-alist
            `(("." . ,(expand-file-name "backups/" user-emacs-directory))))
      (setq auto-save-file-name-transforms
            `((".*" ,(expand-file-name "auto-saves/" user-emacs-directory) t)))

      ;; Track recently opened files (needed for consult-recent-file)
      (recentf-mode 1)

      ;; Remember minibuffer history between sessions (vertico uses this)
      (savehist-mode 1)

      ;; ================================================================
      ;; EVIL — vim modal editing
      ;; ================================================================

      ;; These MUST be set before evil loads or they have no effect.
      (setq evil-want-integration t)
      ;; evil-collection takes over keybinds for non-editing buffers (magit, etc.)
      ;; so tell evil not to set them itself.
      (setq evil-want-keybinding nil)

      (use-package evil
        :init
        ;; Use Emacs 28+'s native undo/redo rather than evil's legacy system.
        ;; Gives you C-/ to undo and C-? to redo.
        (setq evil-undo-system 'undo-redo)
        :config
        (evil-mode 1)

        ;; K shows documentation (mirrors your nvim config's K = LSP hover)
        ;; eldoc-doc-buffer opens a dedicated buffer with the full doc string.
        (evil-define-key 'normal 'global "K"  #'eldoc-doc-buffer)

        ;; gd / gr work via xref, which eglot integrates with automatically.
        (evil-define-key 'normal 'global "gd" #'xref-find-definitions)
        (evil-define-key 'normal 'global "gr" #'xref-find-references))

      ;; evil-collection makes evil keybinds work in special buffers:
      ;; magit hunks, vterm, help windows, org-mode, dired, etc.
      ;; Without it those buffers use Emacs bindings even in normal mode.
      (use-package evil-collection
        :after evil
        :config
        (evil-collection-init))

      ;; ================================================================
      ;; GENERAL.EL — SPC leader key
      ;; ================================================================

      ;; general.el is the standard way to define a leader key in evil-mode.
      ;; SPC only fires in normal/visual/motion states — it never intercepts
      ;; your spacebar while typing in insert mode.
      ;; M-SPC is a fallback that works from insert mode if you ever need it.

      (use-package general
        :after evil
        :config
        (general-evil-setup t)

        (general-create-definer trey/leader-keys
          :keymaps '(normal visual motion)
          :prefix "SPC"
          :global-prefix "M-SPC")

        (trey/leader-keys
          ;; SPC SPC = M-x: the Emacs command palette.
          ;; This is the single most important binding to know.
          "SPC" '(execute-extended-command :wk "M-x")

          ;; ── Find / File (f) ─────────────────────────────
          "f"   '(:ignore t :wk "Find/File")
          "ff"  '(consult-find         :wk "Find files")
          "fg"  '(consult-ripgrep      :wk "Grep files")
          "fb"  '(consult-buffer       :wk "Find buffers")
          "fr"  '(consult-recent-file  :wk "Recent files")
          "fh"  '(consult-info         :wk "Search info manuals")
          "fs"  '(save-buffer          :wk "Save file")

          ;; ── Buffer (b) ──────────────────────────────────
          "b"   '(:ignore t :wk "Buffer")
          "bd"  '(kill-this-buffer :wk "Delete buffer")
          "bn"  '(next-buffer      :wk "Next buffer")
          "bp"  '(previous-buffer  :wk "Previous buffer")

          ;; ── Git (g) ─────────────────────────────────────
          "g"   '(:ignore t :wk "Git")
          "gg"  '(magit-status      :wk "Magit")
          "gl"  '(magit-log-current :wk "Log")

          ;; ── LSP (l) ─────────────────────────────────────
          ;; eglot integrates with xref and flymake automatically,
          ;; so these built-in commands gain LSP superpowers when eglot is active.
          "l"   '(:ignore t :wk "LSP")
          "ld"  '(xref-find-definitions          :wk "Go to definition")
          "lD"  '(xref-find-references           :wk "Find references")
          "la"  '(eglot-code-actions             :wk "Code actions")
          "lf"  '(eglot-format-buffer            :wk "Format buffer")
          "ln"  '(eglot-rename                   :wk "Rename symbol")
          "lx"  '(flymake-show-buffer-diagnostics :wk "Diagnostics")
          "lh"  '(eldoc-doc-buffer               :wk "Hover docs")

          ;; ── Notes / Org (n) ─────────────────────────────
          "n"   '(:ignore t :wk "Notes/Org")
          "nf"  '(org-roam-node-find    :wk "Find/create note")
          "ni"  '(org-roam-node-insert  :wk "Insert link")
          "nb"  '(org-roam-buffer-toggle :wk "Backlinks panel")
          "na"  '(org-agenda            :wk "Agenda")
          "nc"  '(org-capture           :wk "Capture")

          ;; ── Toggle (t) ──────────────────────────────────
          "t"   '(:ignore t :wk "Toggle")
          "tt"  '(vterm                    :wk "Terminal")
          "to"  '(olivetti-mode            :wk "Olivetti (zen write)")
          "tl"  '(display-line-numbers-mode :wk "Line numbers")

          ;; ── Help (h) ────────────────────────────────────
          ;; Uses helpful instead of the built-in describe-* commands.
          "h"   '(:ignore t :wk "Help")
          "hf"  '(helpful-callable :wk "Function")
          "hv"  '(helpful-variable :wk "Variable")
          "hk"  '(helpful-key      :wk "Key")
          "hm"  '(describe-mode    :wk "Mode")))

      ;; ================================================================
      ;; WHICH-KEY — show available keybinds after a prefix
      ;; ================================================================

      ;; Press SPC and pause — which-key shows every binding under that prefix.
      ;; Essential while learning. The :wk labels in general.el above feed into this.
      (use-package which-key
        :config
        (which-key-mode 1)
        (setq which-key-idle-delay 0.3))

      ;; ================================================================
      ;; HELPFUL — richer help buffers
      ;; ================================================================

      ;; helpful replaces the built-in describe-function / describe-variable
      ;; with output that includes the source code, related functions, and
      ;; formatted docstrings. Very useful while learning Emacs internals.
      (use-package helpful
        :commands (helpful-callable helpful-variable helpful-key))

      ;; ================================================================
      ;; MINIBUFFER COMPLETION STACK
      ;; vertico + orderless + marginalia + consult work as a unit.
      ;; ================================================================

      ;; vertico: replaces the default horizontal completion in the echo area
      ;; with a vertical list — makes M-x, find-file, etc. much easier to navigate.
      (use-package vertico
        :config
        (vertico-mode 1))

      ;; orderless: type space-separated parts in any order to filter candidates.
      ;; e.g. "buf del" matches "kill-this-buffer", "next buf" matches "next-buffer".
      (use-package orderless
        :config
        (setq completion-styles '(orderless basic)
              ;; Files still need prefix matching for path completion to work right
              completion-category-overrides
              '((file (styles basic partial-completion)))))

      ;; marginalia: adds annotations alongside completion candidates.
      ;; e.g. shows a function's docstring next to its name in M-x,
      ;; or file permissions next to filenames in find-file.
      (use-package marginalia
        :config
        (marginalia-mode 1))

      ;; consult: enhanced versions of common commands.
      ;; consult-ripgrep, consult-find, consult-buffer, etc. are what SPC f* uses.
      ;; Lazy loaded — only pulled in when you actually call one of these commands.
      (use-package consult
        :commands (consult-find consult-ripgrep consult-buffer
                   consult-recent-file consult-info))

      ;; ================================================================
      ;; CORFU — in-buffer completion popup (like nvim-cmp)
      ;; ================================================================

      ;; corfu shows a popup of completions as you type.
      ;; It uses Emacs's built-in completion system, so it works with eglot (LSP),
      ;; elisp symbols, file paths, and anything else automatically.
      (use-package corfu
        :config
        (global-corfu-mode 1)
        (setq corfu-auto        t     ; show completions automatically (no key needed)
              corfu-auto-delay  0.2   ; wait 200ms before showing
              corfu-auto-prefix 2))   ; start completing after 2 characters

      ;; ================================================================
      ;; TREESITTER — built into Emacs 29, just needs configuration
      ;; ================================================================

      ;; Emacs 29 has native treesitter support via the treesit library.
      ;; The grammar .so files were installed via Nix (treesit-grammars above).
      ;; This remaps traditional major modes to their *-ts-mode equivalents,
      ;; which use treesitter for more accurate syntax highlighting and indentation.
      (setq major-mode-remap-alist
            '((python-mode . python-ts-mode)
              (go-mode     . go-ts-mode)
              (bash-mode   . bash-ts-mode)
              (json-mode   . json-ts-mode)
              (yaml-mode   . yaml-ts-mode)))

      ;; ================================================================
      ;; EGLOT — LSP client (built into Emacs 29)
      ;; ================================================================

      ;; eglot connects to language servers for completion, go-to-definition,
      ;; diagnostics, formatting, etc. It's lighter than lsp-mode and built-in.
      ;;
      ;; IMPORTANT: language servers must be in your PATH.
      ;; Install them in your Nix system or home config, NOT here. e.g.:
      ;;   home.packages = [ pkgs.gopls pkgs.nixd pkgs.pylsp ];
      ;;
      ;; eglot integrates automatically with xref (gd, gr) and flymake (diagnostics).
      (use-package eglot
        :hook
        ((go-ts-mode     . eglot-ensure)  ; needs gopls in PATH
         (python-ts-mode . eglot-ensure)  ; needs pylsp in PATH
         (nix-mode       . eglot-ensure)) ; needs nixd in PATH
        :config
        ;; Don't log every LSP event — noisy and wastes memory
        (setq eglot-events-buffer-size 0)
        ;; Shut down the server when the last buffer of that project closes
        (setq eglot-autoshutdown t))

      ;; ================================================================
      ;; MAGIT — git interface
      ;; ================================================================

      ;; magit is what many people cite as their reason to use Emacs.
      ;; It does everything lazygit does and considerably more.
      ;; SPC g g opens it. Press ? inside magit to see its own keybind help.
      (use-package magit
        :commands (magit-status magit-log-current))

      ;; ================================================================
      ;; VTERM — real terminal emulator inside Emacs
      ;; ================================================================

      ;; vterm uses a C library to emulate a real terminal — unlike eshell,
      ;; it correctly handles full terminal programs: vim inside Emacs, htop,
      ;; color output, etc. SPC t t opens it.
      (use-package vterm
        :commands vterm)

      ;; ================================================================
      ;; ORG MODE — built-in, configured here
      ;; ================================================================

      (use-package org
        ;; olivetti centers the buffer automatically when opening org files
        :hook (org-mode . olivetti-mode)
        :config
        ;; The directory where your org files live.
        ;; org-agenda will look here for TODOs and scheduled items.
        (setq org-directory "~/org")
        (setq org-default-notes-file (concat org-directory "/inbox.org"))

        ;; org-babel: run code blocks directly in org files.
        ;; This is the built-in equivalent of your molten/quarto setup —
        ;; write a #+begin_src python block and run it with C-c C-c.
        (org-babel-do-load-languages
         'org-babel-load-languages
         '((python     . t)
           (shell      . t)
           (emacs-lisp . t)))

        ;; Don't ask "are you sure?" every time you run a code block
        (setq org-confirm-babel-evaluate nil)

        ;; Syntax highlight code inside src blocks
        (setq org-src-fontify-natively t)

        ;; Tab inside a src block behaves as it does in that language's mode
        (setq org-src-tab-acts-natively t)

        ;; Hide the /markers/ *around* ~formatted~ text (cleaner to read)
        (setq org-hide-emphasis-markers t))

      ;; ================================================================
      ;; ORG-MODERN — visual polish for org files
      ;; ================================================================

      ;; org-modern replaces plain-text org markers with cleaner glyphs:
      ;; nicer header bullets, checkbox symbols, table lines, priority tags.
      ;; Stylix handles colors, so no color configuration here.
      (use-package org-modern
        :hook (org-mode . org-modern-mode))

      ;; ================================================================
      ;; OLIVETTI — centered writing buffer
      ;; ================================================================

      ;; olivetti narrows and centers the buffer — good for writing prose.
      ;; Activated automatically in org-mode via the hook above.
      ;; Toggle manually with SPC t o for any buffer.
      (use-package olivetti
        :commands olivetti-mode
        :config
        ;; Width of the text column in characters. Adjust to your monitor.
        (setq olivetti-body-width 100))

      ;; ================================================================
      ;; ORG-ROAM — linked notes / Zettelkasten
      ;; ================================================================

      ;; org-roam builds a graph of linked org files with backlink tracking.
      ;; Think Obsidian but inside Emacs, built on plain org files.
      ;; Uses sqlite to index your note graph.
      ;;
      ;; SPC n f — find or create a note
      ;; SPC n i — insert a link to another note at point
      ;; SPC n b — open the backlinks panel for the current note
      ;;
      ;; You don't need to use this immediately — it's here when you want it.
      (use-package org-roam
        :commands (org-roam-node-find org-roam-node-insert org-roam-buffer-toggle)
        :config
        (setq org-roam-directory (expand-file-name "roam" org-directory))
        ;; Keep the note index in sync as you create/edit notes
        (org-roam-db-autosync-mode))
    '';
  };

  # ── Emacs daemon ──────────────────────────────────────────────────────────
  # The daemon starts once at login and keeps Emacs running in the background.
  # `emacsclient` then connects to it in milliseconds instead of cold-starting.
  # This is separate from the GC and native-comp optimizations above — think of
  # those as making the config fast; the daemon makes opening files instant.
  services.emacs = {
    enable  = true;
    package = config.programs.emacs.finalPackage;
    # Creates desktop entries and sets emacsclient as $EDITOR
    client.enable = true;
  };
}
